// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GroupRecordingInitParameters struct {

	// (String, Deprecated) Deprecated The duration by which to delay the execution of the recording rule.
	// **Deprecated** The duration by which to delay the execution of the recording rule.
	EvaluationDelay *string `json:"evaluationDelay,omitempty" tf:"evaluation_delay,omitempty"`

	// (String) Recording Rule group interval
	// Recording Rule group interval
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) The Organization ID. If not set, the Org ID defined in the provider block will be used.
	// The Organization ID. If not set, the Org ID defined in the provider block will be used.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) The duration by which to delay the execution of the recording rule.
	// The duration by which to delay the execution of the recording rule.
	QueryOffset *string `json:"queryOffset,omitempty" tf:"query_offset,omitempty"`

	// (Block List, Min: 1) (see below for nested schema)
	Rule []GroupRecordingRuleInitParameters `json:"rule,omitempty" tf:"rule,omitempty"`

	// (List of String) Allows aggregating data from multiple tenants while evaluating a rule group.
	// Allows aggregating data from multiple tenants while evaluating a rule group.
	SourceTenants []*string `json:"sourceTenants,omitempty" tf:"source_tenants,omitempty"`
}

type GroupRecordingObservation struct {

	// (String, Deprecated) Deprecated The duration by which to delay the execution of the recording rule.
	// **Deprecated** The duration by which to delay the execution of the recording rule.
	EvaluationDelay *string `json:"evaluationDelay,omitempty" tf:"evaluation_delay,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Recording Rule group interval
	// Recording Rule group interval
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) Recording Rule group namespace
	// Recording Rule group namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The Organization ID. If not set, the Org ID defined in the provider block will be used.
	// The Organization ID. If not set, the Org ID defined in the provider block will be used.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) The duration by which to delay the execution of the recording rule.
	// The duration by which to delay the execution of the recording rule.
	QueryOffset *string `json:"queryOffset,omitempty" tf:"query_offset,omitempty"`

	// (Block List, Min: 1) (see below for nested schema)
	Rule []GroupRecordingRuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`

	// (List of String) Allows aggregating data from multiple tenants while evaluating a rule group.
	// Allows aggregating data from multiple tenants while evaluating a rule group.
	SourceTenants []*string `json:"sourceTenants,omitempty" tf:"source_tenants,omitempty"`
}

type GroupRecordingParameters struct {

	// (String, Deprecated) Deprecated The duration by which to delay the execution of the recording rule.
	// **Deprecated** The duration by which to delay the execution of the recording rule.
	// +kubebuilder:validation:Optional
	EvaluationDelay *string `json:"evaluationDelay,omitempty" tf:"evaluation_delay,omitempty"`

	// (String) Recording Rule group interval
	// Recording Rule group interval
	// +kubebuilder:validation:Optional
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) Recording Rule group namespace
	// Recording Rule group namespace
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The Organization ID. If not set, the Org ID defined in the provider block will be used.
	// The Organization ID. If not set, the Org ID defined in the provider block will be used.
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) The duration by which to delay the execution of the recording rule.
	// The duration by which to delay the execution of the recording rule.
	// +kubebuilder:validation:Optional
	QueryOffset *string `json:"queryOffset,omitempty" tf:"query_offset,omitempty"`

	// (Block List, Min: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Rule []GroupRecordingRuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`

	// (List of String) Allows aggregating data from multiple tenants while evaluating a rule group.
	// Allows aggregating data from multiple tenants while evaluating a rule group.
	// +kubebuilder:validation:Optional
	SourceTenants []*string `json:"sourceTenants,omitempty" tf:"source_tenants,omitempty"`
}

type GroupRecordingRuleInitParameters struct {

	// (String) The PromQL expression to evaluate.
	// The PromQL expression to evaluate.
	Expr *string `json:"expr,omitempty" tf:"expr,omitempty"`

	// (Map of String) Labels to add or overwrite before storing the result.
	// Labels to add or overwrite before storing the result.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the time series to output to.
	// The name of the time series to output to.
	Record *string `json:"record,omitempty" tf:"record,omitempty"`
}

type GroupRecordingRuleObservation struct {

	// (String) The PromQL expression to evaluate.
	// The PromQL expression to evaluate.
	Expr *string `json:"expr,omitempty" tf:"expr,omitempty"`

	// (Map of String) Labels to add or overwrite before storing the result.
	// Labels to add or overwrite before storing the result.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the time series to output to.
	// The name of the time series to output to.
	Record *string `json:"record,omitempty" tf:"record,omitempty"`
}

type GroupRecordingRuleParameters struct {

	// (String) The PromQL expression to evaluate.
	// The PromQL expression to evaluate.
	// +kubebuilder:validation:Optional
	Expr *string `json:"expr" tf:"expr,omitempty"`

	// (Map of String) Labels to add or overwrite before storing the result.
	// Labels to add or overwrite before storing the result.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the time series to output to.
	// The name of the time series to output to.
	// +kubebuilder:validation:Optional
	Record *string `json:"record" tf:"record,omitempty"`
}

// GroupRecordingSpec defines the desired state of GroupRecording
type GroupRecordingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GroupRecordingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupRecordingInitParameters `json:"initProvider,omitempty"`
}

// GroupRecordingStatus defines the observed state of GroupRecording.
type GroupRecordingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupRecordingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GroupRecording is the Schema for the GroupRecordings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,mimir}
type GroupRecording struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rule) || (has(self.initProvider) && has(self.initProvider.rule))",message="spec.forProvider.rule is a required parameter"
	Spec   GroupRecordingSpec   `json:"spec"`
	Status GroupRecordingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupRecordingList contains a list of GroupRecordings
type GroupRecordingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GroupRecording `json:"items"`
}

// Repository type metadata.
var (
	GroupRecording_Kind             = "GroupRecording"
	GroupRecording_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GroupRecording_Kind}.String()
	GroupRecording_KindAPIVersion   = GroupRecording_Kind + "." + CRDGroupVersion.String()
	GroupRecording_GroupVersionKind = CRDGroupVersion.WithKind(GroupRecording_Kind)
)

func init() {
	SchemeBuilder.Register(&GroupRecording{}, &GroupRecordingList{})
}
