// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GroupsInitParameters struct {
}

type GroupsObservation struct {
	AlertingRulesCount *float64 `json:"alertingRulesCount,omitempty" tf:"alerting_rules_count,omitempty"`

	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	RecordingRulesCount *float64 `json:"recordingRulesCount,omitempty" tf:"recording_rules_count,omitempty"`

	RulesCount *float64 `json:"rulesCount,omitempty" tf:"rules_count,omitempty"`
}

type GroupsParameters struct {
}

type RulesInitParameters struct {

	// YAML content containing rule groups. Mutually exclusive with 'content_file'.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Path to YAML file containing rule groups. Mutually exclusive with 'content'.
	ContentFile *string `json:"contentFile,omitempty" tf:"content_file,omitempty"`

	// List of rule group names to ignore from the content. Useful when you want to manage most groups but exclude specific ones.
	// +listType=set
	IgnoreGroups []*string `json:"ignoreGroups,omitempty" tf:"ignore_groups,omitempty"`

	// The namespace for the rule groups
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Explicit list of rule group names to manage. If not specified, all groups in the content will be managed. Use this to manage only specific groups from a larger YAML file.
	// +listType=set
	OnlyGroups []*string `json:"onlyGroups,omitempty" tf:"only_groups,omitempty"`

	// The Organization ID. If not set, the Org ID defined in the provider block will be used.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`
}

type RulesObservation struct {

	// YAML content containing rule groups. Mutually exclusive with 'content_file'.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Path to YAML file containing rule groups. Mutually exclusive with 'content'.
	ContentFile *string `json:"contentFile,omitempty" tf:"content_file,omitempty"`

	// Hash of the rule configuration content
	ContentHash *string `json:"contentHash,omitempty" tf:"content_hash,omitempty"`

	// Details of all managed rule groups
	Groups []GroupsObservation `json:"groups,omitempty" tf:"groups,omitempty"`

	// Number of rule groups managed by this resource
	GroupsCount *float64 `json:"groupsCount,omitempty" tf:"groups_count,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of rule group names to ignore from the content. Useful when you want to manage most groups but exclude specific ones.
	// +listType=set
	IgnoreGroups []*string `json:"ignoreGroups,omitempty" tf:"ignore_groups,omitempty"`

	// List of rule group names actually managed by this resource
	ManagedGroups []*string `json:"managedGroups,omitempty" tf:"managed_groups,omitempty"`

	// The namespace for the rule groups
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Explicit list of rule group names to manage. If not specified, all groups in the content will be managed. Use this to manage only specific groups from a larger YAML file.
	// +listType=set
	OnlyGroups []*string `json:"onlyGroups,omitempty" tf:"only_groups,omitempty"`

	// The Organization ID. If not set, the Org ID defined in the provider block will be used.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// List of all rule names actually managed by this resource
	RuleNames []*string `json:"ruleNames,omitempty" tf:"rule_names,omitempty"`

	// Total number of rules across all managed groups
	TotalRules *float64 `json:"totalRules,omitempty" tf:"total_rules,omitempty"`
}

type RulesParameters struct {

	// YAML content containing rule groups. Mutually exclusive with 'content_file'.
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Path to YAML file containing rule groups. Mutually exclusive with 'content'.
	// +kubebuilder:validation:Optional
	ContentFile *string `json:"contentFile,omitempty" tf:"content_file,omitempty"`

	// List of rule group names to ignore from the content. Useful when you want to manage most groups but exclude specific ones.
	// +kubebuilder:validation:Optional
	// +listType=set
	IgnoreGroups []*string `json:"ignoreGroups,omitempty" tf:"ignore_groups,omitempty"`

	// The namespace for the rule groups
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Explicit list of rule group names to manage. If not specified, all groups in the content will be managed. Use this to manage only specific groups from a larger YAML file.
	// +kubebuilder:validation:Optional
	// +listType=set
	OnlyGroups []*string `json:"onlyGroups,omitempty" tf:"only_groups,omitempty"`

	// The Organization ID. If not set, the Org ID defined in the provider block will be used.
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`
}

// RulesSpec defines the desired state of Rules
type RulesSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RulesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RulesInitParameters `json:"initProvider,omitempty"`
}

// RulesStatus defines the observed state of Rules.
type RulesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RulesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Rules is the Schema for the Ruless API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,mimir}
type Rules struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.__namespace__) || (has(self.initProvider) && has(self.initProvider.__namespace__))",message="spec.forProvider.namespace is a required parameter"
	Spec   RulesSpec   `json:"spec"`
	Status RulesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RulesList contains a list of Ruless
type RulesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Rules `json:"items"`
}

// Repository type metadata.
var (
	Rules_Kind             = "Rules"
	Rules_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Rules_Kind}.String()
	Rules_KindAPIVersion   = Rules_Kind + "." + CRDGroupVersion.String()
	Rules_GroupVersionKind = CRDGroupVersion.WithKind(Rules_Kind)
)

func init() {
	SchemeBuilder.Register(&Rules{}, &RulesList{})
}
