// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type GroupAlertingInitParameters struct {

	// (String) Alerting Rule group interval
	// Alerting Rule group interval
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) The Organization ID. If not set, the Org ID defined in the provider block will be used.
	// The Organization ID. If not set, the Org ID defined in the provider block will be used.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (Block List, Min: 1) (see below for nested schema)
	Rule []RuleInitParameters `json:"rule,omitempty" tf:"rule,omitempty"`

	// (List of String) Allows aggregating data from multiple tenants while evaluating a rule group.
	// Allows aggregating data from multiple tenants while evaluating a rule group.
	SourceTenants []*string `json:"sourceTenants,omitempty" tf:"source_tenants,omitempty"`
}

type GroupAlertingObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Alerting Rule group interval
	// Alerting Rule group interval
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) Alerting Rule group namespace
	// Alerting Rule group namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The Organization ID. If not set, the Org ID defined in the provider block will be used.
	// The Organization ID. If not set, the Org ID defined in the provider block will be used.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (Block List, Min: 1) (see below for nested schema)
	Rule []RuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`

	// (List of String) Allows aggregating data from multiple tenants while evaluating a rule group.
	// Allows aggregating data from multiple tenants while evaluating a rule group.
	SourceTenants []*string `json:"sourceTenants,omitempty" tf:"source_tenants,omitempty"`
}

type GroupAlertingParameters struct {

	// (String) Alerting Rule group interval
	// Alerting Rule group interval
	// +kubebuilder:validation:Optional
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) Alerting Rule group namespace
	// Alerting Rule group namespace
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The Organization ID. If not set, the Org ID defined in the provider block will be used.
	// The Organization ID. If not set, the Org ID defined in the provider block will be used.
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (Block List, Min: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Rule []RuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`

	// (List of String) Allows aggregating data from multiple tenants while evaluating a rule group.
	// Allows aggregating data from multiple tenants while evaluating a rule group.
	// +kubebuilder:validation:Optional
	SourceTenants []*string `json:"sourceTenants,omitempty" tf:"source_tenants,omitempty"`
}

type RuleInitParameters struct {

	// (String) The name of the alert.
	// The name of the alert.
	Alert *string `json:"alert,omitempty" tf:"alert,omitempty"`

	// (Map of String) Annotations to add to each alert.
	// Annotations to add to each alert.
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// (String) The PromQL expression to evaluate.
	// The PromQL expression to evaluate.
	Expr *string `json:"expr,omitempty" tf:"expr,omitempty"`

	// (String) The duration for which the condition must be true before an alert fires.
	// The duration for which the condition must be true before an alert fires.
	For *string `json:"for,omitempty" tf:"for,omitempty"`

	// (String) How long an alert will continue firing after the condition that triggered it has cleared.
	// How long an alert will continue firing after the condition that triggered it has cleared.
	KeepFiringFor *string `json:"keepFiringFor,omitempty" tf:"keep_firing_for,omitempty"`

	// (Map of String) Labels to add or overwrite for each alert.
	// Labels to add or overwrite for each alert.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`
}

type RuleObservation struct {

	// (String) The name of the alert.
	// The name of the alert.
	Alert *string `json:"alert,omitempty" tf:"alert,omitempty"`

	// (Map of String) Annotations to add to each alert.
	// Annotations to add to each alert.
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// (String) The PromQL expression to evaluate.
	// The PromQL expression to evaluate.
	Expr *string `json:"expr,omitempty" tf:"expr,omitempty"`

	// (String) The duration for which the condition must be true before an alert fires.
	// The duration for which the condition must be true before an alert fires.
	For *string `json:"for,omitempty" tf:"for,omitempty"`

	// (String) How long an alert will continue firing after the condition that triggered it has cleared.
	// How long an alert will continue firing after the condition that triggered it has cleared.
	KeepFiringFor *string `json:"keepFiringFor,omitempty" tf:"keep_firing_for,omitempty"`

	// (Map of String) Labels to add or overwrite for each alert.
	// Labels to add or overwrite for each alert.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`
}

type RuleParameters struct {

	// (String) The name of the alert.
	// The name of the alert.
	// +kubebuilder:validation:Optional
	Alert *string `json:"alert" tf:"alert,omitempty"`

	// (Map of String) Annotations to add to each alert.
	// Annotations to add to each alert.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// (String) The PromQL expression to evaluate.
	// The PromQL expression to evaluate.
	// +kubebuilder:validation:Optional
	Expr *string `json:"expr" tf:"expr,omitempty"`

	// (String) The duration for which the condition must be true before an alert fires.
	// The duration for which the condition must be true before an alert fires.
	// +kubebuilder:validation:Optional
	For *string `json:"for,omitempty" tf:"for,omitempty"`

	// (String) How long an alert will continue firing after the condition that triggered it has cleared.
	// How long an alert will continue firing after the condition that triggered it has cleared.
	// +kubebuilder:validation:Optional
	KeepFiringFor *string `json:"keepFiringFor,omitempty" tf:"keep_firing_for,omitempty"`

	// (Map of String) Labels to add or overwrite for each alert.
	// Labels to add or overwrite for each alert.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`
}

// GroupAlertingSpec defines the desired state of GroupAlerting
type GroupAlertingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GroupAlertingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupAlertingInitParameters `json:"initProvider,omitempty"`
}

// GroupAlertingStatus defines the observed state of GroupAlerting.
type GroupAlertingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupAlertingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GroupAlerting is the Schema for the GroupAlertings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,mimir}
type GroupAlerting struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rule) || (has(self.initProvider) && has(self.initProvider.rule))",message="spec.forProvider.rule is a required parameter"
	Spec   GroupAlertingSpec   `json:"spec"`
	Status GroupAlertingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupAlertingList contains a list of GroupAlertings
type GroupAlertingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GroupAlerting `json:"items"`
}

// Repository type metadata.
var (
	GroupAlerting_Kind             = "GroupAlerting"
	GroupAlerting_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GroupAlerting_Kind}.String()
	GroupAlerting_KindAPIVersion   = GroupAlerting_Kind + "." + CRDGroupVersion.String()
	GroupAlerting_GroupVersionKind = CRDGroupVersion.WithKind(GroupAlerting_Kind)
)

func init() {
	SchemeBuilder.Register(&GroupAlerting{}, &GroupAlertingList{})
}
