apiVersion: ruler.mimir.dip.io/v1alpha1
kind: GroupRecording
metadata:
  name: example-recording-rules
spec:
  forProvider:
    namespace: default
    interval: 30s
    rule:
    - expr: up
      record: job:up:count
  providerConfigRef:
    name: default
