apiVersion: ruler.mimir.dip.io/v1beta1
kind: RuleGroupRecording
metadata:
  name: example-recording-rules
spec:
  forProvider:
    name: example_recording
    namespace: default
    interval: 30s
    rule:
    - expr: up
      record: job:up:count
  providerConfigRef:
    name: default
